name: Publish to PyPI
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - mainline
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-package:
    name: Build Package
    if: startsWith(github.ref, 'refs/tags/')  # only release on tag pushes
    runs-on: ubuntu-latest
    outputs:
      run_id: ${{ steps.set_run_id.outputs.run_id }}

    steps:
    - name: Set unique run ID
      id: set_run_id
      run: echo "run_id=${{ github.run_id }}-${{ github.run_number }}" >> $GITHUB_OUTPUT

    # Download and install
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for tags
        persist-credentials: false
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.14"
    - name: Install package with build dependencies
      run: pip install --no-cache-dir -e ".[testing]"

    # Tests
    - name: Run tests with coverage
      run: pytest --cov=kuhl_haus.servers --cov-report=html --cov-report=xml tests -v

    # Build Distribution Package
    - name: Build package
      run: pdm build
    - name: Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions-${{ steps.set_run_id.outputs.run_id }}
        path: dist/

  github-release:
    name: Create GitHub Release
    if: startsWith(github.ref, 'refs/tags/')  # only release on tag pushes
    needs: [build-package]
    runs-on: ubuntu-latest

    permissions:
      contents: write  # IMPORTANT: mandatory for making GitHub Releases
      id-token: write  # IMPORTANT: mandatory for sigstore

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions-${{ needs.build-package.outputs.run_id }}
        path: dist/
    - name: Sign the dists with Sigstore
      uses: sigstore/gh-action-sigstore-python@v3.0.0
      with:
        inputs: >-
          ./dist/*.tar.gz
          ./dist/*.whl
    - name: Create GitHub Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: >-
        gh release create
        "$GITHUB_REF_NAME"
        --repo "$GITHUB_REPOSITORY"
        --notes ""
    - name: Upload artifact signatures to GitHub Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: >-
        gh release upload
        "$GITHUB_REF_NAME" dist/**
        --repo "$GITHUB_REPOSITORY"

  publish-to-testpypi:
    name: Publish to TestPyPI
    if: startsWith(github.ref, 'refs/tags/')  # only release on tag pushes
    needs: [build-package, github-release]
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/kuhl-haus-mdp-servers
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions-${{ needs.build-package.outputs.run_id }}
        path: dist/
    - name: Publish distribution to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        skip-existing: true

  publish-to-pypi:
    name: Publish to PyPI
    if: startsWith(github.ref, 'refs/tags/')  # only release on tag pushes
    needs: [build-package, github-release, publish-to-testpypi]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/kuhl-haus-mdp-servers
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions-${{ needs.build-package.outputs.run_id }}
        path: dist/

    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://upload.pypi.org/legacy/
        skip-existing: true
